version: "2"

services:
  base:
    image: node:12
    volumes:
      - nodemodules:/usr/src/service/node_modules
      - .:/usr/src/service
    working_dir: /usr/src/service
  install:
    extends:
      service: base
    command: yarn && yarn cache clean

volumes:
  nodemodules:
    external: true
